#define NETBSD 1
//#define LINUX 1
#define FEAT_DEBUG 1
#define DEBUG 1
#define FEAT_CMDMON 1
#define FEAT_NTP 1
// #define FEAT_REFCLOCK 1
#define HAVE_LONG_TIME_T 1
#define NTP_ERA_SPLIT (1644776655LL - 18250 * 24 * 3600)
//#define HAVE_IN_PKTINFO 1
//#define FEAT_IPV6 1
#define _GNU_SOURCE 1
#define HAVE_IN6_PKTINFO 1
#define HAVE_CLOCK_GETTIME 1
#define FEAT_ASYNCDNS 1
#define USE_PTHREAD_ASYNCDNS 1
#define HAVE_GETRANDOM 1
// #define HAVE_RECVMMSG 1
// #define HAVE_LINUX_TIMESTAMPING 1
//#define HAVE_LINUX_TIMESTAMPING_RXFILTER_NTP 1
//#define HAVE_LINUX_TIMESTAMPING_OPT_PKTINFO 1
//#define HAVE_LINUX_TIMESTAMPING_OPT_TX_SWHW 1
//#define FEAT_RTC 1
// #define FEAT_PHC 1
//#define HAVE_PTHREAD_SETSCHEDPARAM 1
// #define HAVE_MLOCKALL 1
#define HAVE_SETRLIMIT_MEMLOCK 1
#define FORCE_DNSRETRY 1
#define FEAT_SECHASH 1
#define HAVE_CMAC 1
#define HAVE_SIV 1
#define FEAT_NTS 1
//#define PRIVOPS_ADJUSTTIME 1
//S#define PRIVOPS_ADJUSTTIMEX 1
//#define PRIVOPS_HELPER 1
#define DEFAULT_CONF_FILE "/etc/chrony.conf"
#define DEFAULT_HWCLOCK_FILE ""
#define DEFAULT_PID_FILE "/var/run/chrony/chronyd.pid"
#define DEFAULT_RTC_DEVICE "/dev/rtc"
#define DEFAULT_USER "root"
#define DEFAULT_COMMAND_SOCKET "/var/run/chrony/chronyd.sock"
#define MAIL_PROGRAM "/usr/lib/sendmail"
#define CHRONYC_FEATURES "-READLINE +SECHASH +IPV6 +DEBUG"
#define CHRONYD_FEATURES "+CMDMON +NTP +REFCLOCK +RTC -PRIVDROP -SCFILTER -SIGND +ASYNCDNS +NTS +SECHASH +IPV6 +DEBUG"
#define CHRONY_VERSION "DEVELOPMENT"
