GTEST_PORT_DIR := $(call select_from_ports,googletest)

INC_DIR += $(GTEST_PORT_DIR)/include

CC_OPT += -DGTEST_HAS_RTTI=0
CC_OPT += -DGTEST_HAS_PTHREAD=0
CC_OPT += -DGTEST_HAS_DEATH_TEST=0
CC_OPT += -DGTEST_USE_OWN_FLAGFILE_FLAG_=0
