#define DEFAULT_CONFIG "/etc/umurmur.conf"
#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_FCNTL_H 1
#define HAVE_FTRUNCATE 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_GOOGLE_PROTOBUF_C_PROTOBUF_C_H 1
#define HAVE_INET_NTOA 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBCONFIG 1
#define HAVE_LIBCONFIG_H 1
#define HAVE_LIBCRYPTO 1
#define HAVE_LIBPROTOBUF_C 1
#define HAVE_LIBSSL 1
#define HAVE_LIBZ 1
#define HAVE_LIMITS_H 1
#define HAVE_MEMCHR 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMORY_H 1
#define HAVE_MEMSET 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_POLL 1
#define HAVE_SOCKET 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRDUP 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_STRRCHR 1
#define HAVE_SYSLOG_H 1
#define HAVE_SYS_POLL_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNAME 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1

#define PACKAGE "umurmur"
#define PACKAGE_BUGREPORT "https://github.com/umurmur/umurmur/issues/new"
#define PACKAGE_NAME "umurmur"
#define PACKAGE_STRING "umurmur 0.2.16"
#define PACKAGE_TARNAME "umurmur"
#define PACKAGE_URL "http://github.com/umurmur/umurmur"
#define PACKAGE_VERSION "0.2.16"
#define STDC_HEADERS 1
#define VERSION "0.2.16"
