#define PGSTD std
#define PQXXTR1 std::tr1
/* #undef PQXX_BROKEN_ITERATOR */
/* #undef PQXX_BROKEN_USING_DECL */
#define PQXX_HAVE_AUTO_PTR 1
/* #undef PQXX_HAVE_BOOST_SMART_PTR */
#define PQXX_HAVE_CHAR_TRAITS 1
#define PQXX_HAVE_CPP_PRAGMA_MESSAGE 1
#define PQXX_HAVE_CPP_WARNING 1
#define PQXX_HAVE_GCC_CONST 1
#define PQXX_HAVE_GCC_DEPRECATED 1
#define PQXX_HAVE_GCC_NORETURN 1
#define PQXX_HAVE_GCC_PURE 1
#define PQXX_HAVE_IOS 1
#define PQXX_HAVE_LIMITS 1
#define PQXX_HAVE_LONG_DOUBLE 1
#define PQXX_HAVE_LONG_LONG 1
/* #undef PQXX_HAVE_MOVE */
#define PQXX_HAVE_REVERSE_ITERATOR 1
#define PQXX_HAVE_SHARED_PTR 1
#define PQXX_HAVE_STREAMBUF 1
/* #undef PQXX_HAVE_UNIQUE_PTR */
#define PQXX_TR1_HEADERS 1
