set app_config {
  <start name="julia_fractal">
    <resource name="RAM" quantum="4M"/>
    <route>
      <service name="Nitpicker"> <child name="wm"/> </service>
      <any-service> <parent/> <any-child/> </any-service>
    </route>
  </start>}

set build_components { app/julia_fractal }

set boot_modules {
	julia_fractal
	libc.lib.so
	vfs.lib.so
	libm.lib.so
	stdcxx.lib.so
}

source ${genode_dir}/repos/world/run/nitpicker_app.inc
