lappend import [depot_user]/src/libc \
               [depot_user]/src/vfs \
               [depot_user]/src/stdcxx

set app_config {
  <start name="julia_fractal">
    <resource name="RAM" quantum="8M"/>
    <route>
      <service name="Gui"> <child name="wm"/> </service>
      <any-service> <parent/> <any-child/> </any-service>
    </route>
  </start>}

build { app/julia_fractal }

source ${genode_dir}/repos/world/run/gui_app.inc
